name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-orders-api,${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-orders-worker

    - name: Build and push API Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/ECommerce.Orders.Api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-orders-api:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Worker Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/ECommerce.Orders.Worker/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-orders-worker:latest
        labels: ${{ steps.meta.outputs.labels }}